### ISSUE TITLE
Godot doesn't recognise the plugin

### ISSUE THREAD

**Issue by PudWin14** [newold3/Auto-Slice-Atlas#1]
Hello!

I install the plugin from the assetLib inside the Godot Editor (V4.2.1.stable), but the editor didn't recognise it as an plugin
![Cutter_1](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/6b6af6e4-8e4c-4506-b4e8-0b44adb48586)

![Cutter_2](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/fba99a28-69eb-4a9a-a939-668af422d125)
![Cutter_3](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/7ec52817-a53a-483f-87f0-61fff6b9eed0)
![Cutter_4](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/dafe5890-7284-41f1-93fd-c9ac7c09d222)

**I use the spanish translation

Moving the files, I found that, if you crate a addons folder, like others plugins, and put the main folder of this plugin inside, Godot recognise it and works perfectly.

![Cutter_5](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/115c28c9-438f-4e22-912b-90e607707de3)
![Cutter_6](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/548c24da-882e-42e7-af9e-ed866f7a6c04)
![Cutter_7](https://github.com/newold3/Auto-Slice-Atlas/assets/101060043/43c88d82-2c2c-4f74-86fe-eb9fa13fbe99)

I hope I can help to fix and improve this plugin.

Thanks!

**Comment by newold3** [comment]
Indeed the plugin was missing in the addons folder, I corrected the problem.. Thanks!
